### ISSUE TITLE
Dark mode youtube conflict 

### ISSUE THREAD

**Issue by ntelas** [gurumukhi/YouTubeAdBlocker#1]
Hey. I really like your extension but i found a problem. When Dark mode is enabled, the button is not visible. It's there but not visible.

**Comment by gurumukhi** [comment]
Hey @ntelas, looks like you wanted to report this issue for youtube-queue addon (https://github.com/gurumukhi/youtube-queue-addon/). I have fixed this issue and uploaded fixed version, kindly let me know if you still see any problem. Thanks a lot for reporting this :-) Feel free to reopen the issue if you see any issue again.

**Comment by gurumukhi** [comment]
>> Looks like you wanted to report this issue for youtube-queue addon (https://github.com/gurumukhi/youtube-queue-addon/)

In case I have given wrong link (to report bugs) at any place let me know :-)
