### ISSUE TITLE
It simply does not work at least asof 2020-09 (August 2020)

### ISSUE THREAD

**Issue by succeedmr123** [gurumukhi/YouTubeAdBlocker#2]
Ads blocking just does not work. So, if you want me to dump verbose console output, I may do that.

But, in your development environment you may notice the same.

Best

**Comment by gurumukhi** [comment]
In initial investigation I found it working for me. Can you please provide me debug logs for further investigation?

**Comment by gurumukhi** [comment]
Oh looks like you are right, I see "Skip Ad" DOM changed from `div.videoAdUiSkipContainer` to `span.ytp-ad-skip-button-container`.

Anyone wants to pick this up, feel free to pick it up and raise the PR.

**Comment by gurumukhi** [comment]
Updated the addon with required change - https://addons.mozilla.org/en-US/firefox/addon/ad-free-youtube/. Thanks @succeedmr123 for reporting the issue.
